-- =====================================================================
-- UP: v_ad_performance groups by metric_date, not just snapshot_date
-- =====================================================================
-- Down version: 2026-09-15_v_ad_performance_metric_date.down.sql
--
-- WHY
--   mktg.snap_ad_source was built 2026-09-15 (see CLAUDE.md "Ad source /
--   Windsor") with primary key (snapshot_date, metric_date, source,
--   account) - snapshot_date is the day the ETL ran, metric_date is the
--   day the spend/clicks actually happened. v_ad_performance existed
--   before that ETL leg did, written against a table that held 0 rows, and
--   its GROUP BY never included metric_date. The live effect, confirmed on
--   snapshot 2026-09-15: the view collapsed the entire trailing window
--   (WINDSOR_DATE_PRESET, currently last_365d - 255 distinct metric_dates,
--   2025-12-02 to 2026-09-14) into one row per (snapshot_date, is_paid,
--   source, account). That reads as "spend so far in the trailing
--   window", identical on every day's snapshot bar float drift, not a
--   day-by-day trend - even though snap_ad_source itself already carries
--   full daily granularity. This migration adds metric_date to the GROUP
--   BY so the view stops discarding it.
--
-- WHY DROP INSTEAD OF CREATE OR REPLACE
--   CREATE OR REPLACE VIEW only allows new columns to be appended at the
--   end of the existing column list; it cannot insert metric_date after
--   snapshot_date without erroring on "cannot change name of view column"
--   for every column after it. Dropping loses the grant (same trap as the
--   function-signature case in CLAUDE.md), so it is re-issued below.
--
-- THIS DOES NOT COLLAPSE ANY ROWS - VERIFIED, NOT ASSUMED
--   snap_ad_source's actual primary key already IS
--   (snapshot_date, metric_date, source, account); is_paid is a plain
--   column on that same row, decided once per row when it was written
--   (spend > 0), never recomputed across rows. So grouping by
--   (snapshot_date, metric_date, is_paid, source, account) cannot merge or
--   split anything - every SUM() is a sum of exactly one row. Checked live
--   against all 710 rows for snapshot 2026-09-15: zero duplicate
--   (metric_date, source, account) keys. The GROUP BY is kept anyway,
--   rather than a bare `select *`, so the view keeps behaving correctly if
--   snap_ad_source ever gains a finer grain later (e.g. campaign) without
--   its consumers having to change how they read it.
--
-- ROW-COUNT RISK THIS CREATES - READ BEFORE BUILDING A CONSUMER
--   Every other f_*/v_* object in this schema returns a SMALL number of
--   rows per snapshot_date (single digits to ~18), so "filter server-side
--   on snapshot_date" (CLAUDE.md) is enough by itself to stay under
--   PostgREST's 1000-row cap. This view is different: because every daily
--   sync run re-pulls and re-upserts the WHOLE trailing window under that
--   day's snapshot_date, ONE snapshot_date alone already carries 710 rows
--   today (255 distinct metric_dates cover 2025-12-02 to 2026-09-14, out
--   of the ~287 calendar days between them - some days have zero activity
--   across every source and simply do not appear). At the current pace
--   (710 rows / 255 days = ~2.8 rows/day) a FULL last_365d window
--   projects to roughly 1,015 rows for a single snapshot_date - over the
--   cap, on ONE day's data, with no second dimension left to filter on.
--   Filtering server-side on snapshot_date is necessary here but is not
--   guaranteed sufficient the way it is everywhere else in this schema.
--   Re-count before building a chart against this view; if it is at or
--   near four digits, page through metric_date rather than trusting one
--   unfiltered response.
--
-- Paste PASTE 1 into the Supabase SQL editor and Run. Then paste PASTE 2
-- and Run, and compare against the expected output written beside each
-- query. Do not edit this file to match what you get - re-derive instead,
-- the same discipline as every other migration here.
--
-- No explicit BEGIN. A multi-statement paste is already one implicit
-- transaction in Postgres, so if any statement fails the whole paste
-- rolls back on its own.
-- =====================================================================


-- ============================== PASTE 1 ==============================

drop view if exists mktg.v_ad_performance;

create view mktg.v_ad_performance as
select
    snapshot_date,
    metric_date,
    is_paid,
    source,
    account,
    sum(clicks)      as clicks,
    sum(impressions) as impressions,
    sum(spend)       as spend,
    sum(conversions) as conversions
from mktg.snap_ad_source
group by snapshot_date, metric_date, is_paid, source, account;

grant select on mktg.v_ad_performance to authenticated;

comment on view mktg.v_ad_performance is
  'Ad spend/clicks/impressions/conversions per (metric_date, source, '
  'account), grouped from mktg.snap_ad_source at its own grain - the '
  'GROUP BY never collapses rows, it is there so a future finer grain on '
  'the table keeps working. is_paid is per row (spend > 0 on THAT day), '
  'not a fixed source list: google carries both paid and organic days. '
  'Returns every snapshot_date; filter server-side. Unlike every other '
  'v_*/f_* object here, ONE snapshot_date alone can approach or exceed '
  'the PostgREST 1000-row cap once the trailing window fills out - see '
  'the migration header before assuming snapshot_date filtering alone is '
  'enough.';


-- ============================== PASTE 2 ==============================
-- Verification. Run each and compare. Expected values are the live
-- figures for snapshot 2026-09-15 and will move with Windsor's own
-- trailing window on any later snapshot - re-derive rather than assuming
-- a mismatch is a bug.

-- 2.1  Row count and date span did not change just because the view
--      definition did - the view still reads the same underlying rows.
--
-- expected, snapshot 2026-09-15: 710 rows, 2025-12-02 .. 2026-09-14
select count(*)                as rows,
       min(metric_date)        as earliest,
       max(metric_date)        as latest
from mktg.v_ad_performance
where snapshot_date = '2026-09-15';

-- 2.2  The newest day on its own - proof metric_date is no longer
--      collapsed away. Before this migration this query still returned
--      710 rows (the whole window); after, it returns exactly the rows
--      that happened on that one day.
--
-- expected, snapshot 2026-09-15, metric_date 2026-09-14: one row -
--   google  MultiSensor AI & ICI  is_paid=true  clicks=5  spend=58.19
select source, account, is_paid, clicks, impressions, spend, conversions
from mktg.v_ad_performance
where snapshot_date = '2026-09-15'
  and metric_date = '2026-09-14';

-- 2.3  Nothing merged or split. Summing the new grouped view back down to
--      (snapshot_date, is_paid, source, account) must reproduce exactly
--      what the OLD view's numbers were - same totals, just no longer the
--      only shape available.
--
-- expected, snapshot 2026-09-15, is_paid = true:
--   google    25176.12
--   linkedin  15443.40
--   reddit     8971.20
select source, sum(spend) as spend
from mktg.v_ad_performance
where snapshot_date = '2026-09-15'
  and is_paid
group by source
order by spend desc;

-- 2.4  The row-count caveat from the header, made concrete rather than
--      hypothetical.
--
-- expected, snapshot 2026-09-15: 710 rows total; days_covered somewhat
-- below 287 (2025-12-02 to 2026-09-14 inclusive) because some days carry
-- no activity in any source and never appear at all.
select count(*)                          as rows_this_snapshot,
       count(distinct metric_date)       as distinct_metric_dates
from mktg.v_ad_performance
where snapshot_date = '2026-09-15';
