-- =====================================================================
-- UP 2/3: contacts-by-stage funnel becomes counts only
-- =====================================================================
-- Down version: 2026-09-02_funnel_counts_only.down.sql
--
-- MUST BE APPLIED TOGETHER WITH the sync_to_mktg.py change already
-- committed alongside this file. The ETL no longer sends
-- influenced_value; this paste removes the column. Apply one without the
-- other and the next daily run writes a column that does not exist, or
-- leaves a column nothing populates.
--
-- Paste PASTE 1 into the Supabase SQL editor and Run. Then paste PASTE 2
-- and Run, and compare against the expected output written beside each
-- query. Do not edit this file to match what you get.
--
-- No explicit BEGIN. A multi-statement paste is already one implicit
-- transaction in Postgres, so if any statement fails the whole paste
-- rolls back on its own.
--
-- Ratified 2026-09-02. The funnel answers "where do marketing-sourced
-- contacts sit", which is a count question.
--
-- Why the column goes rather than gets fixed
--   snap_sourced_contact.influenced_value held the total amount of the
--   Net New deals a contact is associated with. Two contacts on one deal
--   each carried that deal's full amount, so summing across contacts
--   counted the deal twice. 12 deals are carried by more than one sourced
--   contact, worth $1,129,524.90 of double count, none Amazon or Galco.
--   sync_to_mktg.py said de-duplication was "the view's job"; the view
--   never did it, and could not, because the table has no deal_id.
--
--   An even-split dollar column would fix the number while keeping the
--   shape that caused it. Removing the column removes the trap: no new
--   column, no attribution model to approve. The funnel is already
--   captioned directional-only because HubSpot auto-advances and skips
--   stages, so a precise dollar on an imprecise funnel was false
--   precision either way.
--
-- Safe to apply: nothing reads either object. /overview does not query
-- them and no contacts-by-stage page exists.
--
-- Order matters. The view depends on the column and the function depends
-- on the table, so both come down before the column does.
-- =====================================================================


-- ============================== PASTE 1 ==============================

-- 1. Drop the duplicate view outright. Unread, and a second body
--    answering the same question as the function. That pattern is what
--    let v_influence_headline drift.
drop view if exists mktg.v_sourced_contacts_by_stage;

-- 2. Dropping a column changes the return type, so create-or-replace
--    would leave a second overload behind and Postgres would then throw
--    "could not choose the best candidate function".
drop function if exists mktg.f_sourced_contacts_by_stage(boolean);

-- 3. Remove the column so no future consumer can pick it up.
alter table mktg.snap_sourced_contact drop column if exists influenced_value;

-- 4. Recreate the function, counts only.
create function mktg.f_sourced_contacts_by_stage(
    include_amazon boolean default true
)
returns table (
    snapshot_date    date,
    lifecycle_stage  text,
    sourced_contacts bigint
)
language sql
stable
set search_path to 'mktg', 'public', 'pg_temp'
as $function$
    select snapshot_date, lifecycle_stage, count(*)
    from snap_sourced_contact
    where not is_internal and (include_amazon or not is_amazon)
    group by snapshot_date, lifecycle_stage;
$function$;

-- 5. Re-grant what the drop discarded.
grant execute on function mktg.f_sourced_contacts_by_stage(boolean) to authenticated;

-- ============================ END PASTE 1 ============================


-- ============================== PASTE 2 ==============================
-- Verification. Run separately, after PASTE 1.

-- (a) expect exactly 8 rows, two columns, in this order:
--       lead                    2669
--       marketingqualifiedlead  1152
--       157687207                218
--       opportunity               83
--       customer                  81
--       salesqualifiedlead        72
--       other                      3
--       evangelist                 1
--     no third column. 4279 contacts across the 8 rows.
select lifecycle_stage, sourced_contacts
  from mktg.f_sourced_contacts_by_stage(true)
 order by sourced_contacts desc;

-- (b) expect exactly one row, one column, value 0
select count(*) as should_be_zero
  from information_schema.columns
 where table_schema = 'mktg'
   and table_name   = 'snap_sourced_contact'
   and column_name  = 'influenced_value';

-- (c) expect exactly one row, one column, value 0
select count(*) as should_be_zero
  from information_schema.views
 where table_schema = 'mktg'
   and table_name   = 'v_sourced_contacts_by_stage';

-- (d) expect exactly one row, one column, value 4297
--     row count unchanged: this migration drops a column, not rows
select count(*) as should_be_4297
  from mktg.snap_sourced_contact
 where snapshot_date = '2026-09-02';

-- ============================ END PASTE 2 ============================
