-- =====================================================================
-- UP 1/3: drop v_influence_headline
-- =====================================================================
-- Down version: 2026-09-02_drop_v_influence_headline.down.sql
--
-- Paste PASTE 1 into the Supabase SQL editor and Run. Then paste PASTE 2
-- and Run, and compare against the expected output written beside each
-- query. Do not edit this file to match what you get.
--
-- No explicit BEGIN. A multi-statement paste is already one implicit
-- transaction in Postgres, so if any statement fails the whole paste
-- rolls back on its own. An explicit BEGIN would need a second Run to
-- COMMIT, and the SQL editor does not reliably hold a session between
-- Run clicks.
--
-- Why this view goes rather than gets repaired. It returned
-- $39,237,605.53 for the same snapshot and the same 228 deals where
-- f_influence_headline returns $11,842,231.76. It looked like it
-- deduplicated and did not:
--
--   JOIN LATERAL (SELECT DISTINCT ON (s2.deal_id) s2.amount_home
--                   FROM snap_influence s2
--                  WHERE s2.snapshot_date = s.snapshot_date
--                    AND s2.deal_id = s.deal_id) ON true
--
-- The lateral is already scoped to one deal_id, so DISTINCT ON has
-- nothing to collapse and the join is 1:1. sum() then ran once per
-- snap_influence row, all 359 of them.
--
-- f_influence_headline answers the same question correctly and carries
-- the include_amazon parameter /overview already passes. Two objects
-- answering one question from two bodies is a permanent trap.
--
-- Confirmed unread: /overview's Influenced Pipeline tile calls
-- f_influence_headline(include_amazon) as an RPC. No page reads the view.
-- =====================================================================


-- ============================== PASTE 1 ==============================

drop view if exists mktg.v_influence_headline;

-- ============================ END PASTE 1 ============================


-- ============================== PASTE 2 ==============================
-- Verification. Run separately, after PASTE 1.

-- (a) expect exactly one row, one column, value 0
select count(*) as should_be_zero
  from information_schema.views
 where table_schema = 'mktg'
   and table_name   = 'v_influence_headline';

-- (b) expect exactly one row: 228 | 11842231.76
select total_deals, influenced_pipeline
  from mktg.f_influence_headline(true);

-- ============================ END PASTE 2 ============================
